name: Build gocryptfs for ARM64

on:
  push:
    branches: [ workflows ]
  pull_request:
    branches: [ workflows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libfuse-dev pkg-config

    - name: Build gocryptfs
      run: |
        go build -v -tags without_openssl .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gocryptfs-arm64
        path: ./gocryptfs
