name: Build gocryptfs for M1 Mac
on:
  push:
    branches: [ workflows ]
  pull_request:
    branches: [ workflows ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout gocryptfs
      uses: actions/checkout@v3
      with:
        repository: rfjakob/gocryptfs
        ref: master
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install macOS dependencies
      run: |
        brew update
        brew install openssl pkg-config
        
    - name: Generate go.sum
      run: go mod tidy
        
    - name: Get version info
      run: echo "version=$(git describe --tags HEAD)" >> $GITHUB_ENV
        
    - name: Build gocryptfs
      run: |
        go build -ldflags "-X github.com/rfjakob/gocryptfs/v2/internal/configfile.GitVersion=${{ env.version }} -X github.com/rfjakob/gocryptfs/v2/internal/configfile.GitVersionFuse=${{ env.version }} -X github.com/rfjakob/gocryptfs/v2/internal/configfile.BuildDate=$(date +%Y-%m-%d)" -o gocryptfs
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gocryptfs-m1
        path: ./gocryptfs