name: Magisk Module Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version number
      id: version
      run: echo "::set-output name=version::v1.0.1"

    - name: Update module.prop version
      run: sed -i "s/version=.*/version=${{ steps.version.outputs.version }}/g" module.prop

    - name: Build Magisk module
      run: |
        # Create the module ZIP file with the desired naming convention
        zip -r gocryptfs-magisk-${{ steps.version.outputs.version }}-release.zip META-INF system install.sh module.prop uninstall.sh

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: ${{ steps.release_draft.outputs.body }}
        draft: false
        prerelease: false

    - name: Upload Magisk module
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gocryptfs-magisk-${{ steps.version.outputs.version }}-release.zip
        asset_name: gocryptfs-magisk-${{ steps.version.outputs.version }}-release.zip
        asset_content_type: application/zip