name: Build static fusermount3 for ARM64
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential meson ninja-build pkg-config libfuse3-dev udev
    - name: Clone libfuse
      run: git clone https://github.com/libfuse/libfuse.git
    - name: Build libfuse
      run: |
        cd libfuse
        mkdir build
        cd build
        meson .. -Ddefault_library=static -Dudevrulesdir=/etc/udev/rules.d
        ninja
        sudo ninja install
    - name: Build fusermount3
      run: |
        cd libfuse/build/util
        ninja fusermount3
    - name: Create static fusermount3 binary
      run: |
        gcc -static -o fusermount3.static libfuse/build/util/fusermount3 -L/usr/local/lib -lpthread -lfuse3
    - name: Strip binary
      run: strip fusermount3.static
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: fusermount3-arm64-static
        path: ./fusermount3.static