name: gocryptfs arm64 Unit Testing
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm64
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    
    - name: Get latest release info
      id: latest_release
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          const releases = response.data.filter(release => 
            release.tag_name.startsWith('arm64-v')
          );
          
          if (releases.length === 0) {
            core.setFailed('No ARM64 releases found');
            return;
          }
          
          const latest = releases.sort((a, b) => 
            new Date(b.created_at) - new Date(a.created_at)
          )[0];
          
          core.setOutput('tag', latest.tag_name);
          core.setOutput('url', latest.assets[0].browser_download_url);
    
    - name: Download gocryptfs binary
      run: |
        mkdir -p system/bin
        curl -L ${{ steps.latest_release.outputs.url }} -o system/bin/gocryptfs
        chmod +x system/bin/gocryptfs
    
    - name: Verify binary
      run: |
        ls -la system/bin
        file system/bin/gocryptfs
    
    - name: Run tests
      run: |
        if [ -f "system/bin/gocryptfs" ]; then
          go test -v ./... -exec ./system/bin/gocryptfs
        else
          echo "gocryptfs binary not found!"
          exit 1
        fi
      shell: bash
