name: gocryptfs arm64 Unit Testing
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm64
    steps:
    - name: Checkout your magisk repository
      uses: actions/checkout@v4
      
    - name: Checkout gocryptfs source repository
      uses: actions/checkout@v4
      with:
        repository: rfjakob/gocryptfs
        path: gocryptfs-source
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libfuse-dev pkg-config fuse
        
    - name: Copy binary to source repository
      run: |
        ls -la system/bin/
        mkdir -p gocryptfs-source/build
        cp system/bin/gocryptfs gocryptfs-source/build/
        chmod +x gocryptfs-source/build/gocryptfs
        
    - name: Prepare test environment in source repo
      working-directory: gocryptfs-source
      run: go mod tidy
        
    - name: Run Go tests with custom binary
      working-directory: gocryptfs-source
      run: |
        # The actual test command may need to be adjusted based on the gocryptfs test structure
        GOFLAGS="-exec $(pwd)/build/gocryptfs" go test -v ./...
