name: gocryptfs arm64 Unit Testing
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm64
    steps:
    - uses: actions/checkout@v4
    
    - name: Download gocryptfs binary
      run: |
        mkdir -p system/bin
        curl -L ${{ steps.latest_release.outputs.url || github.event.repository.html_url }}/releases/latest/download/gocryptfs -o system/bin/gocryptfs
        chmod +x system/bin/gocryptfs
    
    - name: Verify binary
      run: |
        ls -la system/bin
        file system/bin/gocryptfs
    
    - name: Test gocryptfs basic functionality
      run: |
        if [ -f "system/bin/gocryptfs" ]; then
          # Create test directories
          mkdir -p test/cipher test/plain
          
          # Test version output
          ./system/bin/gocryptfs -version
          
          # Initialize a test filesystem
          ./system/bin/gocryptfs -init -quiet test/cipher
          
          # Mount the filesystem
          ./system/bin/gocryptfs test/cipher test/plain
          
          # Create a test file
          echo "Test content" > test/plain/testfile.txt
          
          # Verify the file exists and is encrypted in the cipher directory
          ls -la test/plain
          ls -la test/cipher
          
          # Unmount
          fusermount -u test/plain
          
          echo "Basic functionality test passed!"
        else
          echo "gocryptfs binary not found!"
          exit 1
        fi
      shell: bash
