name: gocryptfs arm64 Unit Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Run tests
      run: |
        chmod +x system/bin/gocryptfs
        go test -v ./... -exec ./system/bin/gocryptfs
      shell: bash